### ISSUE TITLE
Reporte individual de cada persona (datos, publicaciones, tesis, proyectos, ...)

### ISSUE THREAD

**Issue by apiad** [matcom/dashboard#12]
Crear una nueva página de reportes, incluir un tab para el reporte individual, que consiste en seleccionar una persona de la lista de `Person.all()` y mostrar entonces un resumen de sus publicaciones, eventos, tesis, etc. Ver el listado de publicaciones como se genera para poner un formato similar.

**Comment by apiad** [comment]
Casi listo, pero se puede mejorar. Si alguien lo quiere coger y terminar...

**Comment by jmorgadov** [comment]
Olvidé poner el resolves, creo q este issue ya se puede cerrar.
